-- Sample data for Food Delivery System

-- Insert sample users
INSERT OR IGNORE INTO users (name, email, password, role, phone) VALUES
('John Doe', 'john@example.com', 'password123', 'customer', '123-456-7890'),
('Jane Smith', 'jane@example.com', 'password123', 'restaurant_owner', '123-456-7891'),
('Bob Driver', 'bob@example.com', 'password123', 'driver', '123-456-7892');

-- Insert sample addresses
INSERT OR IGNORE INTO addresses (user_id, address_line, city, zip_code) VALUES
(1, 'Block C, Indiranagar', 'Bengaluru', '560038'),
(1, 'Vasant Kunj', 'New Delhi', '110070'),
(1, 'Worli Sea Face', 'Mumbai', '400030');

-- Insert sample restaurants
INSERT OR IGNORE INTO restaurants (name, owner_id, address, phone, description, cuisine, rating, delivery_time, min_order, price_range) VALUES
('Spice Symphony', 2, '100 Feet Rd, Indiranagar, Bengaluru, 560038', '080-555-0101', 'Authentic North Indian favorites with comforting curries.', 'Indian', 4.7, '30-40 min', 500.00, '₹₹'),
('Roll Republic', 2, 'Connaught Place, New Delhi, 110001', '011-555-0102', 'Street-food inspired rolls, chaats and sharable snacks.', 'Street Food', 4.6, '20-30 min', 250.00, '₹'),
('Noodle Nest', 2, 'Linking Road, Bandra West, Mumbai, 400050', '022-555-0103', 'Pan-Asian noodles, dumplings, and fusion bowls.', 'Asian', 4.8, '25-35 min', 400.00, '₹₹'),
('Burger Bistro', 2, 'Jubilee Hills, Hyderabad, 500033', '040-555-0104', 'Gourmet burgers, loaded fries, and creamy shakes.', 'American', 4.5, '18-28 min', 350.00, '₹₹'),
('Green Garden', 2, 'Park Street, Kolkata, 700016', '033-555-0105', 'Healthy bowls, salads, and detox smoothies.', 'Healthy', 4.9, '25-35 min', 450.00, '₹₹'),
('Taco Town', 2, 'MG Road, Pune, 411001', '020-555-0106', 'Build-your-own tacos with vibrant salsas and fillings.', 'Mexican', 4.7, '22-32 min', 300.00, '₹₹'),
('Pasta Piazza', 2, 'Koregaon Park, Pune, 411001', '020-555-0107', 'Classic and creamy pasta plates in an Italian mood.', 'Italian', 4.6, '20-30 min', 550.00, '₹₹'),
('Sushi Studio', 2, 'Banjara Hills, Hyderabad, 500034', '040-555-0108', 'Fresh sushi rolls, sashimi platters, and Japanese favorites.', 'Japanese', 4.8, '28-38 min', 800.00, '₹₹₹'),
('BBQ Barn', 2, 'Koramangala, Bengaluru, 560034', '080-555-0109', 'Smoky meats, loaded platters, and hearty grill combos.', 'Barbecue', 4.5, '30-40 min', 600.00, '₹₹'),
('Sweet Spot', 2, 'Hauz Khas Village, New Delhi, 110016', '011-555-0110', 'Decadent desserts, artisan cakes, and coffee pairings.', 'Desserts', 4.9, '15-25 min', 200.00, '₹'),
('Sunrise Cafe', 2, 'Colaba Causeway, Mumbai, 400001', '022-555-0111', 'Breakfast classics, waffles, and strong coffee all day.', 'Cafe', 4.6, '18-26 min', 300.00, '₹');

-- Insert sample menu items
INSERT OR IGNORE INTO menu_items (restaurant_id, name, description, price, category) VALUES
-- Spice Symphony
(1, 'Butter Chicken', 'Creamy tomato-based curry with tender chicken.', 16.99, 'Curries'),
(1, 'Paneer Tikka Masala', 'Grilled cottage cheese in rich masala gravy.', 15.99, 'Curries'),
(1, 'Lamb Rogan Josh', 'Slow-cooked lamb curry with aromatic spices.', 18.99, 'Curries'),
(1, 'Garlic Naan Basket', 'Freshly baked naan with garlic butter.', 5.50, 'Breads'),
(1, 'Saffron Rice', 'Fragrant basmati rice with saffron.', 4.50, 'Sides'),
(1, 'Chaat Platter', 'Crispy papdi and sev with tangy chutneys.', 8.99, 'Starters'),
(1, 'Tandoori Paneer Skewers', 'Spiced paneer grilled to perfection.', 11.99, 'Starters'),
(1, 'Dal Makhani', 'Slow-cooked black lentils with cream.', 12.50, 'Breads & Sides'),
(1, 'Mango Lassi', 'Sweet mango yogurt drink.', 4.99, 'Beverages'),
(1, 'Gulab Jamun', 'Soft milk dumplings in sweet syrup.', 6.50, 'Desserts'),
-- Roll Republic
(2, 'Kathi Roll', 'Spiced chicken roll with chutney and onions.', 8.99, 'Rolls'),
(2, 'Paneer Roll', 'Grilled paneer with veggies and sauces.', 8.49, 'Rolls'),
(2, 'Aloo Tikki Burger', 'Potato patty with special chutney.', 7.99, 'Snacks'),
(2, 'Pani Puri', 'Crispy puris with tangy pani.', 5.50, 'Chaats'),
(2, 'Dahi Puri', 'Crunchy puris with yogurt and chutneys.', 5.99, 'Chaats'),
(2, 'Samosa Chaat', 'Samosa topped with chickpeas and chutneys.', 6.99, 'Chaats'),
(2, 'Corn Cheese Balls', 'Golden fried balls with corn and cheese.', 7.50, 'Snacks'),
(2, 'Masala Fries', 'Spiced potato fries with mayo dip.', 4.99, 'Sides'),
(2, 'Chai Latte', 'Classic masala tea latte.', 3.99, 'Beverages'),
(2, 'Jalebi', 'Crispy syrup-soaked sweet spirals.', 4.99, 'Desserts'),
-- Noodle Nest
(3, 'Chicken Chow Mein', 'Stir-fried noodles with veggies and chicken.', 14.50, 'Noodles'),
(3, 'Veg Hakka Noodles', 'Soft noodles tossed with fresh vegetables.', 12.99, 'Noodles'),
(3, 'Beef Teriyaki Noodles', 'Savory teriyaki beef with noodles.', 15.99, 'Noodles'),
(3, 'Prawn Wonton Soup', 'Clear broth with prawns and wontons.', 9.99, 'Soups'),
(3, 'Miso Soup', 'Delicate miso soup with tofu and seaweed.', 4.99, 'Soups'),
(3, 'Gyoza Platter', 'Pan-fried dumplings with dipping sauce.', 10.99, 'Starters'),
(3, 'Asian Salad Bowl', 'Crunchy greens with sesame ginger dressing.', 11.50, 'Salads'),
(3, 'Spicy Szechuan Tofu', 'Tofu in fiery Szechuan sauce.', 13.99, 'Mains'),
(3, 'Coconut Rice', 'Fragrant rice cooked with coconut milk.', 4.99, 'Sides'),
(3, 'Lychee Cooler', 'Refreshing lychee and mint drink.', 5.50, 'Beverages'),
-- Burger Bistro
(4, 'Classic Beef Burger', 'Juicy beef patty with cheese and pickles.', 12.99, 'Burgers'),
(4, 'Truffle Mushroom Burger', 'Burger with sautéed mushrooms and truffle mayo.', 14.99, 'Burgers'),
(4, 'Spicy Chicken Burger', 'Crispy chicken with spicy slaw.', 13.50, 'Burgers'),
(4, 'Loaded Fries', 'Fries loaded with cheese, bacon and jalapeños.', 8.99, 'Sides'),
(4, 'Onion Rings', 'Crispy beer-battered onion rings.', 6.50, 'Sides'),
(4, 'Caesar Salad', 'Romaine lettuce with Caesar dressing.', 9.50, 'Salads'),
(4, 'Milkshake Trio', 'Choose chocolate, vanilla, or strawberry.', 6.99, 'Beverages'),
(4, 'BBQ Chicken Wrap', 'Smoky chicken with coleslaw in wrap.', 11.99, 'Wraps'),
(4, 'Veggie Burger', 'Grilled veggie patty with avocado.', 12.50, 'Burgers'),
(4, 'Chocolate Brownie', 'Warm brownie with ice cream.', 7.50, 'Desserts'),
-- Green Garden
(5, 'Quinoa Power Bowl', 'Quinoa, greens, roasted veggies and tahini.', 13.99, 'Bowls'),
(5, 'Kale Caesar Salad', 'Crisp kale with parmesan and croutons.', 11.99, 'Salads'),
(5, 'Avocado Toast', 'Sourdough toast with smashed avocado.', 10.99, 'Breakfast'),
(5, 'Green Smoothie', 'Spinach, apple, banana, and almond milk.', 6.50, 'Beverages'),
(5, 'Buddha Bowl', 'Tofu, brown rice, greens and miso dressing.', 14.50, 'Bowls'),
(5, 'Sweet Potato Fries', 'Crispy baked sweet potato fries.', 5.99, 'Sides'),
(5, 'Grilled Veggie Wrap', 'Charred veggies with hummus.', 12.50, 'Wraps'),
(5, 'Chia Pudding', 'Berry chia pudding with granola.', 7.99, 'Desserts'),
(5, 'Protein Pancakes', 'Oats pancakes with banana and honey.', 12.99, 'Breakfast'),
(5, 'Iced Matcha Latte', 'Matcha with cold milk and honey.', 5.99, 'Beverages'),
-- Taco Town
(6, 'Carnitas Tacos', 'Slow-cooked pork tacos with salsa verde.', 10.99, 'Tacos'),
(6, 'Fish Tacos', 'Crispy fish tacos with cabbage slaw.', 11.99, 'Tacos'),
(6, 'Veggie Taco Trio', 'Grilled veggies, black beans, and avocado.', 9.99, 'Tacos'),
(6, 'Quesadilla', 'Melted cheese with peppers and onions.', 8.99, 'Mains'),
(6, 'Nachos Grande', 'Loaded nachos with cheese and pico de gallo.', 9.50, 'Snacks'),
(6, 'Mexican Street Corn', 'Corn with chili, mayo and cheese.', 5.99, 'Sides'),
(6, 'Guacamole Dip', 'Fresh guacamole with chips.', 6.50, 'Sides'),
(6, 'Horchata', 'Cinnamon rice milk drink.', 4.99, 'Beverages'),
(6, 'Churros', 'Cinnamon sugar churros with chocolate.', 6.99, 'Desserts'),
(6, 'Salsa Trio', 'Mild, medium, and spicy salsas.', 3.99, 'Sides'),
-- Pasta Piazza
(7, 'Fettuccine Alfredo', 'Creamy parmesan pasta with herbs.', 14.99, 'Pasta'),
(7, 'Spaghetti Bolognese', 'Classic meat sauce pasta.', 15.50, 'Pasta'),
(7, 'Pesto Penne', 'Basil pesto with pine nuts and parmesan.', 13.99, 'Pasta'),
(7, 'Garlic Breadsticks', 'Warm garlic breadsticks with dip.', 5.99, 'Sides'),
(7, 'Caprese Salad', 'Tomato, mozzarella, basil, olive oil.', 10.99, 'Salads'),
(7, 'Mushroom Risotto', 'Creamy risotto with wild mushrooms.', 16.99, 'Mains'),
(7, 'Tiramisu', 'Classic espresso-soaked dessert.', 7.99, 'Desserts'),
(7, 'Panna Cotta', 'Creamy vanilla dessert with berry compote.', 7.50, 'Desserts'),
(7, 'Italian Soda', 'Sparkling fruit soda.', 4.99, 'Beverages'),
(7, 'Meatball Starter', 'House-made meatballs in tomato sauce.', 9.99, 'Starters'),
-- Sushi Studio
(8, 'California Roll', 'Crab, avocado and cucumber.', 12.50, 'Sushi Rolls'),
(8, 'Spicy Tuna Roll', 'Tuna with spicy mayo.', 13.50, 'Sushi Rolls'),
(8, 'Salmon Sashimi', 'Fresh sliced salmon.', 15.99, 'Sashimi'),
(8, 'Vegetable Tempura', 'Lightly fried vegetables.', 8.99, 'Starters'),
(8, 'Miso Soup', 'Warm miso soup with tofu.', 4.99, 'Soups'),
(8, 'Seaweed Salad', 'Sesame seaweed salad.', 5.99, 'Sides'),
(8, 'Dragon Roll', 'Eel and avocado on rice.', 16.99, 'Sushi Rolls'),
(8, 'Udon Noodle Bowl', 'Thick noodles in savory broth.', 13.99, 'Noodles'),
(8, 'Matcha Cheesecake', 'Green tea cheesecake slice.', 7.99, 'Desserts'),
(8, 'Green Tea', 'Traditional hot green tea.', 3.50, 'Beverages'),
-- BBQ Barn
(9, 'Smoked Brisket Platter', 'Tender brisket with house sauce.', 18.99, 'Platters'),
(9, 'BBQ Chicken Wings', 'Sticky wings with smoky glaze.', 12.50, 'Starters'),
(9, 'Pulled Pork Sandwich', 'Slow-roast pork with coleslaw.', 13.99, 'Sandwiches'),
(9, 'Cornbread Muffin', 'Sweet cornbread muffin.', 3.99, 'Sides'),
(9, 'Mac & Cheese', 'Creamy macaroni and cheese.', 6.99, 'Sides'),
(9, 'Grilled Veg Skewers', 'Seasonal vegetables with herbs.', 9.50, 'Sides'),
(9, 'BBQ Ribs Half Rack', 'Fall-off-the-bone ribs.', 19.99, 'Platters'),
(9, 'Coleslaw', 'Crunchy coleslaw with dressing.', 4.99, 'Sides'),
(9, 'Sweet Tea', 'Iced sweet tea.', 3.99, 'Beverages'),
(9, 'Apple Pie Slice', 'Warm apple pie with whipped cream.', 6.99, 'Desserts'),
-- Sweet Spot
(10, 'Chocolate Lava Cake', 'Warm cake with molten center.', 8.99, 'Desserts'),
(10, 'Red Velvet Cupcake', 'Creamy frosting over red cake.', 5.99, 'Desserts'),
(10, 'Berry Cheesecake', 'Fresh berries over rich cheesecake.', 7.99, 'Desserts'),
(10, 'Creme Brulee', 'Caramelized sugar crust dessert.', 7.50, 'Desserts'),
(10, 'Belgian Waffle', 'Waffle with berries and cream.', 9.99, 'Breakfast'),
(10, 'Hot Chocolate', 'Rich hot chocolate with marshmallows.', 4.99, 'Beverages'),
(10, 'Strawberry Smoothie', 'Fresh strawberry blend.', 5.99, 'Beverages'),
(10, 'Fruit Parfait', 'Yogurt with granola and fruit.', 6.99, 'Breakfast'),
(10, 'Caramel Latte', 'Espresso with caramel milk.', 4.99, 'Beverages'),
(10, 'Mini Donut Stack', 'Assorted glazed mini donuts.', 6.50, 'Desserts'),
-- Sunrise Cafe
(11, 'Avocado Toast', 'Sourdough toast with avocado mash.', 9.99, 'Breakfast'),
(11, 'Eggs Benedict', 'Poached eggs with hollandaise sauce.', 13.99, 'Breakfast'),
(11, 'Pancake Stack', 'Fluffy pancakes with maple syrup.', 11.50, 'Breakfast'),
(11, 'Granola Bowl', 'Yogurt, granola, nuts and berries.', 8.50, 'Bowls'),
(11, 'Breakfast Burrito', 'Eggs, sausage, cheese and salsa.', 10.99, 'Breakfast'),
(11, 'French Toast', 'Cinnamon French toast with berries.', 12.50, 'Breakfast'),
(11, 'Smoked Salmon Bagel', 'Cream cheese and smoked salmon.', 12.99, 'Sandwiches'),
(11, 'Cappuccino', 'Classic Italian espresso drink.', 4.99, 'Beverages'),
(11, 'Fresh Fruit Salad', 'Seasonal fruit bowl.', 7.99, 'Sides'),
(11, 'Lemon Tart', 'Tangy lemon tart with whipped cream.', 6.99, 'Desserts');